name = "whscyasfbu46374hvhvey45769vh5751huqlgmfjurtdgdse"
print(name[::1])
print(name[::2])
print(name[::3])
print(name[::4])
print(name[::-1])
print(name[::-2])
print(name[0:9])
dou=name.find("vhve")
fou=name.rfind("vhve")
print(dou)
print(fou)
