#coding=utf-8
name = input("请输入您的名字：")
qq = input("请输入您的QQ:")
phone = input("请输入您的手机号码：")
adress = input("请输入您的地址：")
print("--"*20)
print("姓名：%s"%name)
print("Q  Q：%s"%qq)
print("手机号：%s"%phone)
print("公司地址：%s"%adress)
print("--"*20)
print("--"*20)

num1 = input("请输入第一个数：")
num2 = input("请输入第二个数：")
result = int(num1) + int(num2)
print("%s+%s=%d"%(num1,num2,result))
